export const stockData = [
    {
      image: "images/foto_1.jpg",
      name: "Magda",
      ras: "Buldog",
      gender: "teef",
      age: 5,
      location:"Brussel",
      id:1,
    },
    {
        image: "images/foto_2.jpg",
        name: "blacly",
        ras: "Mopshond",
        gender: "reu",
        age: 5,
        location:"Brussel",
        id:2,
    },
    {
        image: "images/foto_3.jpg",  
        name: "Evert",
        ras: "Franse Buldog",
        gender: "teef",
        age: 7,
        location:"Antwerpen",
        id:3,
    },
    {
        image: "images/foto_4.jpg",  
        name: "Simon",
        ras: "samojeed",
        gender: "reu",
        age: 4,
        location:"Brussel",
        id:4,
    },
    {
        image: "images/foto_5.jpg",  
        name: "LILLY",
        ras: "Labrador retriever",
        gender: "teef",
        age: "2",
        location:"Brussel",
        id:5,
    },
    {
        image: "images/foto_6.jpg",  
        name: "FRANKIE",
        ras: "Bordercollie",
        gender: "reu",
        age: "2",
        location:"Limburg",
        id:6,
    },
    {
        image: "images/foto_7.jpg",  
        name: "HOLLY",
        ras: "Beagle",
        gender: "teef",
        age: "4",
        location:"Limburg",
        id:7,
    },
    {
        image: "images/foto_8.jpg",  
        name: "MOCHA",
        ras: "Mechelse herder",
        gender: "teef",
        age: "3",
        location:"Limburg",
        id:8,
    },
    {
        image: "images/foto_9.jpg",  
        name: "COOKIE",
        ras: "Labradoodle",
        gender: "teef",
        age: "3",
        location:"Geel",
        id:9,
    },
    {
        image: "images/foto_10.jpg",  
        name: "ROXIE",
        ras: "Golden retriever",
        gender: "teef",
        age: "3",
        location:"Limburg",
        id:10,
    },
    {
        image: "images/foto_11.jpg",  
        name: "PEPPER",
        ras: "Shiba",
        gender: "reu",
        age: "2",
        location:"Brussel",
        id:11,
    },
    {
        image: "images/foto_12.jpg",  
        name: "SASHA",
        ras: "Cockerspaniël",
        gender: "teef",
        age: "1",
        location:"Brussel",
        id:12,
    },
    {
        image: "images/foto_13.jpg",  
        name: "DIESEL",
        ras: "Australische herder",
        gender: "reu",
        age: "6",
        location:"Limburg",
        id:13,
    },
    {
        image: "images/foto_14.jpg",  
        name: "OREO",
        ras: "Berner sennenhond",
        gender: "reu",
        age: "7",
        location:"West-Vlaanderen",
        id:14,
    },
    {
        image: "images/foto_15.jpg",  
        name: "BUDDY",
        ras: "Duitse herder",
        gender: "reu",
        age: "6",
        location:"Limburg",
        id:15,
    },
    {
        image: "images/foto_16.jpg",  
        name: "CHICO",
        ras: "Maltezer",
        gender: "reu",
        age: "4",
        location:"Oost-Vlaanderen",
        id:16,
    },
    {
        image: "images/foto_17.jpg",  
        name: "BO",
        ras: "Zwitserse herder",
        gender: "reu",
        age: "5",
        location:"Brussel",
        id:17,
    },
    {
        image: "images/foto_18.jpg",  
        name: "DUKE",
        ras: "Akita",
        gender: "reu",
        age: "3",
        location:"Oost-Vlaanderen",
        id:18,
    },
    {
        image: "images/foto_19.jpg",  
        name: "BUSTER",
        ras: "Shih Tzu",
        gender: "reu",
        age: "2",
        location:"Oost-Vlaanderen",
        id:19,
    },
    {
        image: "images/foto_20.jpg",  
        name: "HANK",
        ras: "Havanezer",
        gender: "reu",
        age: "8",
        location:"Brussel",
        id:20,
    },
    {
        image: "images/foto_21.jpg",  
        name: "BENTLEY",
        ras: "Dashond - Teckel",
        gender: "reu",
        age: "6",
        location:"Vlaams-Brabant",
        id:21,
    },
    {
        image: "images/foto_22.jpg",  
        name: "OLLIE",
        ras: "Alaskan Klee Kai",
        gender: "reu",
        age: "4",
        location:"Vlaams-Brabant",
        id:22,
    },
    {
        image: "images/foto_23.jpg",  
        name: "ENZO",
        ras: "Basset Hound",
        gender: "reu",
        age: "3",
        location:"Vlaams-Brabant",
        id:23,
    },
    {
        image: "images/foto_24.jpg",  
        name: "FREYA",
        ras: "Havanezer",
        gender: "teef",
        age: "1",
        location:"Brussel",
        id:24,
    },
    {
        image: "images/foto_25.jpg",  
        name: "WILLOW",
        ras: "Sheltie",
        gender: "teef",
        age: "4",
        location:"Brussel",
        id:25,
    },
    {
        image: "images/foto_26.jpg",  
        name: "SOPHIE",
        ras: "Anatolische herder",
        gender: "teef",
        age: "5",
        location:"Oost-Vlaanderen",
        id:26,
    },
    {
        image: "images/foto_27.jpg",  
        name: "XENA",
        ras: "Duitse dog",
        gender: "teef",
        age: "7",
        location:"Vlaams-Brabant",
        id:27,
    },
    {
        image: "images/foto_28.jpg",  
        name: "RUDY",
        ras: "Chow Chow",
        gender: "reu",
        age: "6",
        location:"Vlaams-Brabant",
        id:28,
    },
    {
        image: "images/foto_29.jpg",  
        name: "CHANCE",
        ras: "Jackrussellterriër",
        gender: "teef",
        age: "6",
        location:"West-Vlaanderen",
        id:29,
    },
    {
        image: "images/foto_30.jpg",  
        name: "CASSIUS",
        ras: "Dogo Argentino",
        gender: "reu",
        age: "4",
        location:"West-Vlaanderen",
        id:30,
    },
    {
        image: "images/foto_31.jpg",  
        name: "PECKER",
        ras: "Engelse Bulldog",
        gender: "reu",
        age: "5",
        location: "Antwerpen",
        id:31,
    },
    {
        image: "images/foto_32.jpg",  
        name: "JOSEPH",
        ras: "Franse Bulldog",
        gender: "reu",
        age: "7",
        location: "Antwerpen",
        id:32,
    },
    {
     
        image: "images/foto_33.jpg",  
        name: "LADY",
        ras: "Beagle",
        gender: "teef",
        age: "9",
        location: "West-Vlaanderen",
        id:33,
    },
    {
     
        image: "images/foto_34.jpg",  
        name: "HECCIE",
        ras: "Toypoodle",
        gender: "teef",
        age: "6 maanden",
        location: "West-Vlaanderen",
        id:34,
    },
    {
     
        image: "images/foto_35.jpg",  
        name: "CHUBBY",
        ras: "Pomeranian",
        gender: "teef",
        age: "6",
        location: "Vlaams-Brabant",
        id:35,
    },
    {
     
        image: "images/foto_36.jpg",  
        name: "BERNARD",
        ras: "Pitbull",
        gender: "reu",
        age: "2",
        location: "Brussel",
        id:36,
    },
    {
     
        image: "images/foto_37.jpg",  
        name: "BETTY",
        ras: "Italiaanse Windhond",
        gender: "teef",
        age: "1",
        location: "Limburg",
        id:37,
    },   
    {
     
        image: "images/foto_38.jpg",  
        name: "SIMONI",
        ras: "Komondor",
        gender: "reu",
        age: "4",
        location: "Oost-Vlaanderen",
        id:38,
    },
    {
     
        image: "images/foto_39.jpg",  
        name: "SHARPAY",
        ras: "Shar-Pei",
        gender: "teef",
        age: "4",
        location: "Oost-Vlaanderen",
        id:39,
    },
    {
     
        image: "images/foto_40.jpg",  
        name: "CELESTE",
        ras: "Shih Tzu",
        gender: "teef",
        age: "3",
        location: "Brussel",
        id:40,
    },
    {
     
        image: "images/foto_41.jpg",  
        name: "KOBI",
        ras: "Chinese naakthond",
        gender: "reu",
        age: "5",
        location: "Vlaams-Brabant",
        id:41,
    },

  ];
